"""DAX validation harness.

Validates DAX code generated by AI across 6 dimensions:
1. Syntax
2. Semantics (executes in sandbox)
3. Performance (estimated cost)
4. Scope (references allowed tables/columns)
5. RLS safety (doesn't leak with RLS active)
6. Naming convention
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum

import structlog

logger = structlog.get_logger()


class ValidationCheck(str, Enum):
    SYNTAX = "syntax"
    SEMANTIC = "semantic"
    PERFORMANCE = "performance"
    SCOPE = "scope"
    RLS = "rls"
    NAMING = "naming"


@dataclass
class ValidationResult:
    """Result of DAX validation."""

    is_valid: bool
    checks: dict[ValidationCheck, bool] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    estimated_cost_ms: float | None = None
    row_count: int | None = None
    measure_name: str | None = None

    def to_markdown(self) -> str:
        """Format as a human-readable Markdown report."""
        lines = ["## 🧪 Validação DAX", ""]

        if self.measure_name:
            lines.append(f"**Medida:** `{self.measure_name}`")
            lines.append("")

        status_emoji = {True: "✅", False: "❌"}
        lines.append("| Check | Status |")
        lines.append("|---|---|")
        for check, passed in self.checks.items():
            lines.append(f"| {check.value.title()} | {status_emoji[passed]} |")

        if self.estimated_cost_ms is not None:
            lines.append("")
            lines.append(f"**Performance estimada:** {self.estimated_cost_ms:.0f}ms")

        if self.row_count is not None:
            lines.append(f"**Linhas retornadas:** {self.row_count}")

        lines.append("")
        if self.is_valid:
            lines.append("**Veredicto: ✅ APROVADO**")
        else:
            lines.append("**Veredicto: ❌ REPROVADO**")
            lines.append("")
            lines.append("**Erros:**")
            for err in self.errors:
                lines.append(f"- {err}")

        if self.warnings:
            lines.append("")
            lines.append("**Avisos:**")
            for warn in self.warnings:
                lines.append(f"- {warn}")

        return "\n".join(lines)


# Naming convention: Vendas.Receita Total BRL, Vendas.Margem %, etc.
NAMING_PATTERN = re.compile(
    r"^[A-Z][a-zA-ZçÇãÃéÉ]+"  # Domain (PascalCase, accents ok)
    r"\."  # dot separator
    r"[A-Za-zÀ-ÿ0-9 \[\]%/_-]+$"  # Description with allowed chars
)


def matches_naming_convention(measure_name: str) -> bool:
    """Check if measure name follows the naming convention."""
    return bool(NAMING_PATTERN.match(measure_name))


def estimate_query_cost(dax_code: str) -> float:
    """Estimate DAX query cost in milliseconds (heuristic)."""
    cost = 50.0  # base

    heavy_funcs = {
        "FILTER(": 200,
        "CALCULATETABLE(": 150,
        "ADDCOLUMNS(": 100,
        "SUMMARIZE(": 100,
        "GROUPBY(": 100,
        "TOPN(": 80,
        "CROSSJOIN(": 150,
        "UNION(": 80,
    }
    for func, penalty in heavy_funcs.items():
        cost += dax_code.count(func) * penalty

    # Iterators
    iterator_count = sum(1 for it in ["SUMX(", "AVERAGEX(", "COUNTX(", "MAXX("] if it in dax_code)
    cost += iterator_count * 50

    # Table references
    table_refs = len(set(re.findall(r"'([^']+)'", dax_code)))
    cost += table_refs * 20

    return cost


def extract_references(dax_code: str) -> set[str]:
    """Extract table and column references from DAX code."""
    # Table references in single quotes: 'table_name'
    tables = set(re.findall(r"'([^']+)'", dax_code))
    # Column references: [column] or table[column]
    columns = set(re.findall(r"\[([^\]]+)\]", dax_code))
    return tables | columns


def is_select_only_dax(dax_code: str) -> bool:
    """Check if DAX is a SELECT-only query (no side effects)."""
    forbidden = ["CREATE", "ALTER", "DELETE", "DROP", "INSERT", "UPDATE", "TRUNCATE"]
    upper = dax_code.upper()
    return not any(f" {kw} " in upper or upper.startswith(kw) for kw in forbidden)


class DAXValidator:
    """Validates DAX code generated by AI."""

    def __init__(
        self,
        max_cost_ms: float = 5000.0,
        allowed_symbols: set[str] | None = None,
    ):
        self.max_cost_ms = max_cost_ms
        self.allowed_symbols = allowed_symbols or set()

    async def validate(
        self,
        dax_code: str,
        *,
        syntax_check: bool = True,
        semantic_check: bool = True,
        measure_name: str | None = None,
        rls_test_callback=None,
    ) -> ValidationResult:
        """Run all validation checks and return a comprehensive result."""
        result = ValidationResult(is_valid=True, measure_name=measure_name)

        # 1. Syntax check (placeholder — would use pbi-tools in production)
        if syntax_check:
            try:
                # Simplified: check balanced parentheses
                if dax_code.count("(") != dax_code.count(")"):
                    raise ValueError("Unbalanced parentheses")
                if dax_code.count("[") != dax_code.count("]"):
                    raise ValueError("Unbalanced brackets")
                result.checks[ValidationCheck.SYNTAX] = True
            except Exception as e:
                result.checks[ValidationCheck.SYNTAX] = False
                result.errors.append(f"Sintaxe: {e}")

        # 2. Semantic check (placeholder — would execute in sandbox)
        if semantic_check and result.checks.get(ValidationCheck.SYNTAX, False):
            # In production: execute in AI-Playground workspace via XMLA
            result.checks[ValidationCheck.SEMANTIC] = True
            result.row_count = 1

        # 3. Performance estimate
        cost = estimate_query_cost(dax_code)
        result.estimated_cost_ms = cost
        result.checks[ValidationCheck.PERFORMANCE] = cost < self.max_cost_ms
        if not result.checks[ValidationCheck.PERFORMANCE]:
            result.errors.append(
                f"Performance: {cost:.0f}ms > {self.max_cost_ms:.0f}ms"
            )

        # 4. Scope check
        if self.allowed_symbols:
            refs = extract_references(dax_code)
            forbidden = refs - self.allowed_symbols
            # Filter out measures (which are referenced as [Name], not [Table.Column])
            forbidden = {r for r in forbidden if not r[0].isupper() or " " in r}
            result.checks[ValidationCheck.SCOPE] = len(forbidden) == 0
            if forbidden:
                result.errors.append(f"Escopo: refs não permitidas: {forbidden}")
        else:
            result.checks[ValidationCheck.SCOPE] = True

        # 5. RLS check (if callback provided)
        if rls_test_callback:
            try:
                rls_safe = await rls_test_callback(dax_code)
                result.checks[ValidationCheck.RLS] = rls_safe
                if not rls_safe:
                    result.errors.append("RLS: query pode vazar dados entre roles")
            except Exception as e:
                result.checks[ValidationCheck.RLS] = False
                result.errors.append(f"RLS check falhou: {e}")
        else:
            result.checks[ValidationCheck.RLS] = True

        # 6. Naming convention
        if measure_name:
            result.checks[ValidationCheck.NAMING] = matches_naming_convention(measure_name)
            if not result.checks[ValidationCheck.NAMING]:
                result.errors.append(
                    f"Naming: '{measure_name}' não segue convenção "
                    "(formato: 'Dominio.Nome Medida [formato]')"
                )

        # Final verdict
        result.is_valid = all(result.checks.values()) if result.checks else False

        logger.info(
            "dax_validated",
            is_valid=result.is_valid,
            measure=measure_name,
            checks_passed=sum(1 for v in result.checks.values() if v),
            checks_total=len(result.checks),
        )

        return result
